(function(root,factory){
  const api=factory(root,root&&root.document,root&&root.EB_UI,root&&root.ElementBoundCards);
  if(typeof module==='object'&&module.exports)module.exports=api;
  if(root)root.EB_TomeLessons=api;
})(typeof globalThis!=='undefined'?globalThis:this,function(root,document,UI,catalog){
  'use strict';
  const byName=new Map(Object.entries(catalog?.BASE||{}).flatMap(([element,cards])=>cards.map(card=>[card[0],{element,name:card[0],cost:card[1],attack:card[2],health:card[3]}])));for(const [element,card] of Object.entries(catalog?.TECH||{}))byName.set(card[0],{element,name:card[0],cost:card[3]});byName.set('Tide Brute',{element:'WATER',name:'Tide Brute',cost:0,attack:3,health:4});
  const sayLines={
    'lesson-i':['Tap the rival.','That is the whole goal. Everything else is how.'],
    'lesson-ii':['Spend 3 Essence.','Full. Anything left waits for next turn.'],
    'lesson-iii':['Summon it.','It waits one turn.','Now it can attack.'],
    'lesson-iv':['Tap the glowing card.','Burning is set. Now cash it in.','3 damage instead of 2. That is a combo.'],
    'lesson-v':['Guard holds the Bender.','Answer the attack.','Armor took the first point.','Passing is a choice too. Save the Response for the attack that matters.'],
    'lesson-vi':['Play a Fire card.','Now an Earth card.',"Resonance. Magma's cards wake up."],
    'lesson-vii':['','','Empty deck: 2 damage.','Again: 3 damage. It keeps growing.']
  };
  function el(tag,className,text){const node=document.createElement(tag);if(className)node.className=className;if(text!==undefined)node.textContent=text;return node}
  function icon(name,label){return UI.icon(name,{label})}
  function medallion(element,muted=false){const img=el('img',`tl-medallion${muted?' is-muted':''}`);img.src=`assets/medallions/${element.toLowerCase()}.webp`;img.alt='';return img}
  function plate(label,element,hp,{hint=false,status='',onClick=null,rival=false}={}){const node=el(onClick?'button':'div',`tl-plate${hint?' tl-hint':''}`);if(onClick){node.type='button';node.dataset.action='1';node.addEventListener('click',onClick)}node.dataset.plate=label.toLowerCase();node.append(medallion(element,rival),el('strong','',label),icon('heart','Vitality'),el('b','tl-value',String(hp)));if(status)node.append(icon(status,status));return node}
  function miniCard(name,{hint=false,onClick=null,disabled=false,overrideAttack=null,status=''}={}){const card=byName.get(name)||{element:'WATER',name,cost:0,attack:overrideAttack,health:0};const button=el('button',`tl-card${hint?' tl-hint':''}`);button.type='button';button.dataset.card=name;button.disabled=disabled;button.setAttribute('aria-disabled',String(disabled));button.setAttribute('aria-label',`Play ${name} (${card.cost} Essence)`);button.append(el('span','tl-cost',String(card.cost)),medallion(card.element),el('strong','tl-card-name',name));if(card.attack!==undefined&&card.attack!==null){const stats=el('span','tl-stats');stats.append(icon('sword','Attack'),el('b','',String(overrideAttack??card.attack)),icon('heart','Health'),el('b','',String(card.health)));if(status)stats.append(icon(status,status));button.append(stats)}if(onClick){button.dataset.action='1';button.addEventListener('click',onClick)}return button}
  function delta(oldValue,newValue,amount,bonus=''){const change=el('span','tl-change');change.append(el('s','',String(oldValue)),el('b','',String(newValue)),el('i','tl-delta',amount));if(bonus)change.append(el('small','',bonus));return change}
  function slot(child=null){const node=el('div','tl-slot');node.setAttribute('aria-label',child?'Occupied field slot':'Empty slot');if(child)node.append(child);else node.append(el('span','','Empty slot'));return node}
  function row(className,...children){const node=el('div',`tl-row ${className}`);node.append(...children.filter(Boolean));return node}
  function pulse(board){board.classList.remove('is-pulsing');void board.offsetWidth;board.classList.add('is-pulsing')}
  function mount(pageId,tome){const wrap=el('section','tl-demo'),board=el('div','tl-board'),say=el('p','tl-say');say.setAttribute('aria-live','polite');wrap.append(board,say);let step=0,complete=false,auto=0;
    function setSay(index){say.classList.remove('is-changing');void say.offsetWidth;say.textContent=sayLines[pageId][index]||'';say.classList.add('is-changing')}
    function finish(){complete=true;const controls=el('div','tl-finish'),again=el('button','ghost','Again');again.type='button';again.addEventListener('click',()=>{wrap.classList.add('is-resetting');setTimeout(()=>{step=0;complete=false;render();wrap.classList.remove('is-resetting')},150)});controls.append(again);if(pageId==='lesson-vii'){const start=el('button','tome-chip tl-hint','Start the Trials ›');start.type='button';start.addEventListener('click',()=>root.goTrials());controls.append(start)}else if(!['lesson-iv','lesson-v'].includes(pageId)){const next=el('button','tome-chip tl-hint','Next lesson ›');next.type='button';next.dataset.action='1';next.addEventListener('click',()=>tome.flipTo(tome.current+1,{clearTrail:true,focus:true}));controls.append(next)}else requestAnimationFrame(()=>{const target=wrap.closest('.tome-page')?.querySelector('.tome-try');target?.classList.add('tl-hint');target?.focus({preventScroll:true})});wrap.append(controls)}
    function advance(next){step=next;render();const target=wrap.querySelector('.tl-hint');if(target)requestAnimationFrame(()=>target.focus({preventScroll:true}))}
    function render(){clearTimeout(auto);board.replaceChildren();wrap.querySelector('.tl-finish')?.remove();wrap.closest('.tome-page')?.querySelector('.tome-try')?.classList.remove('tl-hint');
      if(pageId==='lesson-i'){const rival=plate('Rival','FIRE',step?27:30,{hint:step===0,rival:true,onClick:()=>advance(1)}),you=plate('You','FIRE',30,{onClick:()=>pulse(board)});if(step)rival.append(delta(30,27,'−3'));board.append(row('tl-rival',rival),row('tl-you',you));setSay(step);if(step)finish()}
      if(pageId==='lesson-ii'){let essence=step===0?3:step===1?1:0;const gems=row('tl-essence',...Array.from({length:3},(_,i)=>{const g=icon('essence','Essence');if(i>=essence)g.classList.add('is-spent');return g}));const hand=row('tl-hand');const order=step===0?['Cinder Adept','Ember Guard','Flare Hawk']:step===1?['Cinder Adept','Flare Hawk']:['Flare Hawk'];for(const name of order){const cost=byName.get(name).cost,affordable=cost<=essence,preferred=(step===0&&name==='Ember Guard')||(step===1&&name==='Cinder Adept');hand.append(miniCard(name,{hint:preferred,onClick:affordable?()=>advance(step+1):()=>pulse(board),disabled:!affordable}))}board.append(gems,hand);setSay(step>=2?1:0);if(step>=2)finish()}
      if(pageId==='lesson-iii'){const slots=row('tl-field',slot(),slot(step?miniCard('Flare Hawk',{status:step===1?'hourglass':'',hint:false}):null),slot());const hand=row('tl-hand');if(step===0)hand.append(miniCard('Flare Hawk',{hint:true,onClick:()=>advance(1)}));if(step===1){const next=el('button','ghost tl-hint','Next turn');next.type='button';next.dataset.action='1';next.addEventListener('click',()=>advance(2));hand.append(next)}if(step===2)slots.querySelector('.tl-card').classList.add('is-ready');board.append(slots,hand);setSay(step);if(step===2)finish()}
      if(pageId==='lesson-iv'){const rival=plate('Rival','FIRE',step===2?7:10,{rival:true,status:step>=1?'burning':''});if(step===2)rival.append(delta(10,7,'−3','−2'));const hand=row('tl-hand');if(step===0)hand.append(miniCard('Cinder Adept',{hint:true,onClick:()=>advance(1)}),miniCard('Flame Burst',{disabled:true}));else if(step===1)hand.append(miniCard('Flame Burst',{hint:true,onClick:()=>advance(2)}));board.append(row('tl-rival',rival),hand);setSay(step);if(step===2)finish()}
      if(pageId==='lesson-v'){const rival=row('tl-rival',miniCard('Tide Brute',{overrideAttack:3}));const field=row('tl-field',miniCard('Earthen Guard',{status:'guard'}),miniCard('Boulder Ram',{status:step===2?'armor':''}));board.append(rival,field,row('tl-you',plate('You','EARTH',30)));if(step===0){setSay(0);auto=setTimeout(()=>{if(!wrap.isConnected)return;rival.querySelector('.tl-card').classList.add('is-lunging');field.querySelector('[data-card="Earthen Guard"]').classList.add('is-guard-flash');auto=setTimeout(()=>{if(wrap.isConnected)advance(1)},300)},600)}else if(step===1){const window=el('div','tl-response');window.append(el('strong','','Response Window'));const stone=el('button','ghost tl-hint','Stonewall'),pass=el('button','ghost','Pass');stone.type=pass.type='button';stone.dataset.action=pass.dataset.action='1';stone.addEventListener('click',()=>advance(2));pass.addEventListener('click',()=>advance(3));window.append(stone,pass);board.append(window);setSay(1)}else{const ram=field.querySelector('[data-card="Boulder Ram"]');ram.append(delta(5,step===2?3:2,step===2?'−2':'−3',step===2?'−3':''));setSay(step===2?2:3);finish()}}
      if(pageId==='lesson-vi'){const ring=el('div',`tl-resonance step-${step}`);ring.append(medallion('FIRE'),el('span','tl-half tl-half-fire'),medallion('MAGMA',step<2),el('span','tl-half tl-half-earth'),medallion('EARTH'));if(step===2)ring.append(el('strong','','Resonance'));const hand=row('tl-hand');if(step===0)hand.append(miniCard('Cinder Adept',{hint:true,onClick:()=>advance(1)}),miniCard('Stone Initiate'));if(step===1)hand.append(miniCard('Stone Initiate',{hint:true,onClick:()=>advance(2)}));board.append(ring,hand);setSay(step);if(step===2)finish()}
      if(pageId==='lesson-vii'){const hp=step>=3?5:step>=2?8:10,deck=row(`tl-deck${step>=2?' is-empty':''}`,icon('deck','Deck'),step>=1?delta(1,0,''):el('b','tl-value','1')),hand=row('tl-hand');if(step>=1)hand.append(miniCard('Ember Guard',{}));const draw=el('button',`ghost${step<3?' tl-hint':''}`,'Draw');draw.type='button';draw.dataset.action='1';draw.addEventListener('click',()=>advance(step+1));board.append(row('tl-you',plate('You','FIRE',hp)),deck);if(step<3)board.append(draw);board.append(hand);if(step===2)board.querySelector('.tl-plate').append(delta(10,8,'−2'));if(step===3){board.querySelector('.tl-plate').append(delta(8,5,'−3'));board.append(el('div','tl-seal','Exhaustion grows'))}setSay(step);if(step===3)finish()}
    }
    render();board.addEventListener('click',event=>{const button=event.target.closest('button');if(event.target===board||(button&&!button.dataset.action))pulse(board)});return wrap
  }
  const STORAGE_KEY='ebTomeOpened';
  function initNudge(){const button=document?.querySelector('.home-links button:last-child');if(!button)return false;let show=false;try{show=root.localStorage.getItem(STORAGE_KEY)!=='1'}catch(_error){return false}if(!show)return false;const badge=el('span','tome-start-badge','Start here');button.append(badge);button.setAttribute('aria-label','How to Play, start here');return true}
  function markOpened(){try{root.localStorage.setItem(STORAGE_KEY,'1')}catch(_error){}const button=document?.querySelector('.home-links button:last-child');button?.querySelector('.tome-start-badge')?.remove();if(button)button.removeAttribute('aria-label')}
  return{mount,sayLines,STORAGE_KEY,initNudge,markOpened};
});
