(function(root,factory){
  const api=factory(root,root&&root.document,root&&root.EB_UI,root&&root.EB_TOME,root&&root.EB_TomeLessons);
  if(typeof module==='object'&&module.exports)module.exports=api;
  if(root)root.EB_Tome=api;
})(typeof globalThis!=='undefined'?globalThis:this,function(root,document,UI,data,lessons){
  'use strict';
  const state={root:null,book:null,pages:[],nodes:[],tabs:[],current:0,trail:[],opened:false,built:false,reduce:false,drag:null,timer:0};
  const titleIndex=new Map((data?.pages||[]).map((page,index)=>[page.title,index]));
  const ALIASES={ATK:'Attack ⚔',HP:'Health ♡',Essence:'Essence',Initiative:'Initiative'};let linkHandler=null;
  function resolveTitle(term){const title=ALIASES[term]||term;return titleIndex.has(title)?title:null}
  const chapterFirst=new Map((data?.chapters||[]).map(chapter=>[chapter.id,(data?.pages||[]).findIndex(page=>page.chapter===chapter.id)]));
  function node(tag,className,text){const el=document.createElement(tag);if(className)el.className=className;if(text!==undefined)el.textContent=text;return el}
  function icon(name,label){return UI.icon(name,{label})}
  function medallion(element,className=''){const image=node('img',`tome-medallion ${className}`);image.src=`assets/medallions/${element.toLowerCase()}.webp`;image.alt='';return image}
  function plain(value=''){return String(value).replace(/\*\*/g,'')}
  function appendLinked(container,text){
    const parts=String(text||'').split(/(\[\[[^\]]+\]\])/g);for(const part of parts){const match=part.match(/^\[\[([^\]]+)\]\]$/);if(!match){container.append(document.createTextNode(part));continue}const button=node('button','tome-link',match[1]);button.type='button';const handler=linkHandler;button.addEventListener('click',()=>(handler||followLink)(match[1]));container.append(button)}
  }
  function linkChip(title){const button=node('button','tome-chip',`${title} ›`);button.type='button';const handler=linkHandler;button.addEventListener('click',event=>{event.stopPropagation();(handler||followLink)(title)});return button}
  function cardChip(name){const button=node('button','tome-card-chip',name);button.type='button';button.setAttribute('aria-label',`Show card: ${name}`);button.addEventListener('click',event=>{event.stopPropagation();peekCard(name,button)});return button}
  function facts(page){const row=node('div','tome-facts');for(const [key,label] of [['on','On'],['lasts','Lasts'],['stacks','Stacks']]){const badge=node('span','tome-fact');badge.append(node('small','',label),node('strong','',page.facts[key]));row.append(badge)}return row}
  const DEMO_ART={
    'Attack ⚔':[{i:'sword'},{b:'3'},'=','deals 3'],'Health ♡':[{i:'heart'},{s:'5'},'→',{b:'2'}],'Essence ◆':[{i:'essence'},{s:'3'},'→',{b:'1'}],
    'Response Window':[{i:'sword'},'→',{i:'hourglass'},{b:'30s'}],'Resonance':[{i:'fire'},'+',{i:'earth'},'=',{i:'magma'}],
    'Burning':[{i:'burning'},{s:'2'},'→',{b:'3'}],'Soaked':[{i:'soaked'},{s:'4'},'→',{b:'2'}],'Flow':[{i:'deck'},{b:'Keep'},'/',{b:'Bottom'}],
    'Armor':[{i:'armor'},{s:'−3'},'→',{b:'−2'}],'Guard':[{i:'sword'},'→',{i:'guard'},'≠',{i:'heart'}],'Seeded':[{i:'seeded'},'→',{i:'growth'}],
    'Growth':[{i:'growth'},{b:'+1'},{i:'sword'},'max 3'],'Charged':[{i:'charged'},{b:'+1'}],'Chain':['1','·','2','·',{b:'3'},{i:'lightning'}],
    'Momentum':[{i:'momentum'},{i:'sword'},{s:'3'},'→',{b:'4'}],'Weakened':[{i:'weakened'},{i:'sword'},{b:'−1'}]
  };
  function staticDemo(page){const art=DEMO_ART[page.title];if(!art)return null;const demo=node('div','tome-demo');demo.setAttribute('role','img');demo.setAttribute('aria-label',page.demo);for(const token of art){let part;if(typeof token==='string')part=node('span','tome-demo-op',token);else if(token.i){part=icon(token.i);part.classList.add('tome-demo-icon')}else part=node(token.s?'s':'b',token.s?'tome-demo-old':'tome-demo-new',token.s||token.b);part.setAttribute('aria-hidden','true');demo.append(part)}return demo}
  const GLYPHS={'⚔':['sword','attack'],'♡':['heart','health'],'◆':['essence','Essence']};
  function glyphify(rootNode){const walker=document.createTreeWalker(rootNode,NodeFilter.SHOW_TEXT),targets=[];while(walker.nextNode())if(/[⚔♡◆]/.test(walker.currentNode.nodeValue))targets.push(walker.currentNode);for(const text of targets){if(text.parentElement?.closest('.tome-title')){text.nodeValue=text.nodeValue.replace(/\s*[⚔♡◆]/g,'');continue}const fragment=document.createDocumentFragment();for(const part of text.nodeValue.split(/([⚔♡◆])/)){if(!part)continue;if(GLYPHS[part]){const glyph=icon(GLYPHS[part][0],GLYPHS[part][1]);glyph.classList.add('tome-glyph');fragment.append(glyph)}else fragment.append(document.createTextNode(part))}text.replaceWith(fragment)}return rootNode}
  function ribbon(){if(!state.trail.length)return null;const previous=state.pages[state.trail[state.trail.length-1]],button=node('button','tome-ribbon',`‹ Back to ${previous.title}`);button.type='button';button.addEventListener('click',()=>{const target=state.trail.pop();flipTo(target,{focus:true})});return button}
  function renderContents(body){
    const groups=[['Part One · First Lessons',state.pages.map((p,i)=>[p,i]).filter(([p])=>p.kind==='lesson')],['Part Two · The Glossary',state.pages.map((p,i)=>[p,i]).filter(([p])=>['term','symbol','glance','index'].includes(p.kind)).filter(([p])=>p.kind==='glance'||p.kind==='index'||p.title==='Attack ⚔')]];
    for(const [heading,items] of groups){body.append(node('h3','tome-section-title',heading));const list=node('div','tome-contents-list');for(const [page,index] of items){const button=node('button','tome-contents-row');button.type='button';const name=node('span','tome-contents-name');if(page.kind==='lesson')name.append(node('b','tome-contents-numeral',page.label.split(' · ').pop()),document.createTextNode(page.title));else name.textContent=page.title==='Attack ⚔'?'Core Terms & Symbols':page.title;button.append(name,node('small','',String(index+1)));button.addEventListener('click',()=>flipTo(index,{clearTrail:true,focus:true}));list.append(button)}body.append(list)}
  }
  function renderGlance(body,page){const table=node('div','tome-glance');for(const item of page.table){const row=node('div','tome-glance-row');row.append(item.icon==='—'?node('span','tome-glance-icon','—'):icon(item.icon,item.effect));const link=node('button','tome-glance-name',item.effect);link.type='button';link.addEventListener('click',()=>followLink(item.effect));row.append(link,node('span','tome-glance-element',item.element),node('span','tome-glance-what',item.what),node('small','',`${item.lasts} · ${item.stacks}`));table.append(row)}body.append(table)}
  function renderIndex(body){for(const [label,elements] of [['Prime',['FIRE','WATER','EARTH','NATURE','LIGHTNING','AIR']],['Hybrid',['MAGMA','BLOOM','STORM']]]){body.append(node('h3','tome-section-title',label));const grid=node('div','tome-element-grid');for(const element of elements){const button=node('button','tome-element-button');button.type='button';button.setAttribute('aria-label',element[0]+element.slice(1).toLowerCase());button.append(medallion(element),node('span','',element[0]+element.slice(1).toLowerCase()));button.addEventListener('click',()=>flipTo(titleIndex.get(element[0]+element.slice(1).toLowerCase()),{clearTrail:true,focus:true}));grid.append(button)}body.append(grid)}body.append(node('p','tome-index-hint','Tap an element, or use the tabs on the page edge.'))}
  function tryButton(element){const info={FIRE:'Flame',WATER:'Tides',EARTH:'Stone',NATURE:'Roots',LIGHTNING:'Storms',AIR:'Winds'},button=node('button','primary tome-try',`Try it · Trial of ${info[element]}`);button.type='button';button.addEventListener('click',()=>{root.goTrials();requestAnimationFrame(()=>requestAnimationFrame(()=>{const target=document.querySelector(`.trial-map-node[data-element="${element}"]`);if(target)root.EB_Trials.openChapter(element,target)}))});return button}
  function renderPage(page,index,opts={}){
    const article=node('article','tome-page');article.dataset.pageId=page.id;article.setAttribute('aria-hidden','true');const scroll=node('div','tome-page-scroll'),back=opts.peek?opts.ribbon:ribbon();if(back)scroll.append(back);scroll.append(node('div','tome-kind',page.label));const title=node('h2','tome-title');title.tabIndex=-1;if(page.kind==='element')title.append(medallion(page.element,'tome-title-medallion'));else title.append(icon(page.icon||'book'));title.append(document.createTextNode(page.title));scroll.append(title,node('div','tome-ornament'));
    if(page.archivist)scroll.append(node('p','tome-narr',page.archivist));
    if(page.kind==='contents')renderContents(scroll);else if(page.kind==='index')renderIndex(scroll);else if(page.kind==='glance')renderGlance(scroll,page);else{
      if(page.deckLine){const deck=node('p','tome-deck-line');deck.style.setProperty('--c',`var(--eb-el-${page.element.toLowerCase()})`);deck.textContent=plain(page.deckLine);scroll.append(deck)}
      if(page.rules){const rules=node('div','tome-rule');for(const line of String(page.rules).split(/(?<=\.)\s+/)){const p=node('p');appendLinked(p,line);rules.append(p)}scroll.append(rules)}
      if(page.kind==='lesson')scroll.append(lessons.mount(page.id,api));
      if(page.rule){const rule=node('p','tome-rule');appendLinked(rule,page.rule);scroll.append(rule)}
      if(page.facts)scroll.append(facts(page));if(page.demo&&page.kind!=='lesson'){const demo=staticDemo(page);if(demo)scroll.append(demo)}
      if(page.confuse){const box=node('div','tome-confuse');box.append(node('b','','≠'),node('small','','Don’t confuse with'));const copy=node('p');appendLinked(copy,page.confuse);box.append(copy);scroll.append(box)}
      if(page.seenOn?.length){scroll.append(node('h3','tome-section-title','Seen on'));const chips=node('div','tome-chips');for(const card of page.seenOn)chips.append(cardChip(card));scroll.append(chips)}
      for(const [field,label] of [['seeAlso','See also'],['inChapter','In this chapter'],['parents','Parents']])if(page[field]?.length){scroll.append(node('h3','tome-section-title',label));const chips=node('div','tome-chips');for(const link of page[field])chips.append(linkChip(link));scroll.append(chips)}
      if(page.hybrid){scroll.append(node('h3','tome-section-title','Hybrid'));const chips=node('div','tome-chips');chips.append(linkChip(page.hybrid));scroll.append(chips)}
      if(page.response){scroll.append(node('h3','tome-section-title','Response'),node('div','tome-response',page.response))}if(page.tryIt&&!opts.peek)scroll.append(tryButton(page.tryIt));
    }
    article.append(scroll);return glyphify(article);
  }
  function sectionLabel(page){if(page.kind==='contents')return'Contents';if(page.kind==='lesson')return'First Lessons';if(page.kind==='glance')return'At a Glance';if(page.kind==='index')return'Elements';if(page.chapter==='core')return'Core Terms';return page.chapter[0]+page.chapter.slice(1).toLowerCase()}
  function renderWindow(){for(let index=0;index<state.nodes.length;index++){const visible=Math.abs(index-state.current)<=2,node=state.nodes[index];node.hidden=!visible;node.style.zIndex=String(state.nodes.length-index);node.classList.toggle('is-past',index<state.current);node.classList.toggle('is-current',index===state.current);node.setAttribute('aria-hidden',String(index!==state.current))}const page=state.pages[state.current];state.root.querySelector('.tome-nav-label').textContent=`${sectionLabel(page)} · ${state.current+1}`;state.root.querySelector('.tome-prev').disabled=state.current===0;state.root.querySelector('.tome-next').disabled=state.current===state.pages.length-1;for(const tab of state.tabs)tab.setAttribute('aria-current',tab.dataset.chapter===page.chapter?'page':'false');state.root.querySelector('.tome-live').textContent=`${page.title}, page ${state.current+1} of ${state.pages.length}`}
  function rebuildCurrent(){const old=state.nodes[state.current],fresh=renderPage(state.pages[state.current],state.current);old.replaceWith(fresh);state.nodes[state.current]=fresh}
  function flipTo(index,{push=false,clearTrail=false,focus=false}={}){index=Math.max(0,Math.min(state.pages.length-1,index));if(index===state.current){if(focus)state.nodes[index].querySelector('.tome-title')?.focus({preventScroll:true});return}if(push){state.trail.push(state.current);state.trail=state.trail.slice(-10)}if(clearTrail)state.trail=[];clearTimeout(state.timer);state.book.classList.add('is-flipping');state.current=index;rebuildCurrent();renderWindow();state.reduce=root.matchMedia?.('(prefers-reduced-motion: reduce)').matches;state.timer=setTimeout(()=>{state.book.classList.remove('is-flipping');if(focus)state.nodes[index].querySelector('.tome-title')?.focus({preventScroll:true})},state.reduce?150:620)}
  function followLink(title){const index=titleIndex.get(title);if(index!==undefined)flipTo(index,{push:true,focus:true})}
  function bindSwipe(stage){stage.addEventListener('click',event=>{if(!state.suppressClick)return;state.suppressClick=false;event.preventDefault();event.stopPropagation()},true);stage.addEventListener('pointerdown',event=>{if(event.button!==0||state.drag)return;state.drag={id:event.pointerId,x:event.clientX,y:event.clientY,time:performance.now(),moved:false,dx:0}});stage.addEventListener('pointermove',event=>{const drag=state.drag;if(!drag||drag.id!==event.pointerId)return;const dx=event.clientX-drag.x,dy=event.clientY-drag.y;if(!state.drag.moved){if(Math.abs(dy)>8&&Math.abs(dy)>Math.abs(dx)){state.drag=null;return}if(Math.abs(dx)>8){state.drag.moved=true;try{stage.setPointerCapture(event.pointerId)}catch(_){}state.book.classList.add('is-dragging')}}if(!state.drag.moved)return;event.preventDefault();drag.dx=dx;const width=stage.clientWidth||1,progress=Math.max(-1,Math.min(1,-dx/width)),current=state.nodes[state.current],previous=state.nodes[state.current-1];if(progress>=0){if(previous)previous.style.transform='';if(state.current<state.nodes.length-1)current.style.transform=`rotateY(${(-178*progress).toFixed(1)}deg)`}else{current.style.transform='';if(previous)previous.style.transform=`rotateY(${(-178*(1+progress)).toFixed(1)}deg)`}});const end=event=>{const drag=state.drag;if(!drag||drag.id!==event.pointerId)return;state.drag=null;if(!drag.moved)return;state.suppressClick=true;setTimeout(()=>{state.suppressClick=false},0);const dx=event.type==='pointercancel'?drag.dx:event.clientX-drag.x,elapsed=Math.max(1,performance.now()-drag.time),speed=Math.abs(dx)/elapsed,go=Math.abs(dx)>stage.clientWidth*.25||speed>.3,target=state.current+(dx<0?1:-1);state.book.classList.remove('is-dragging');for(const node of state.nodes)if(node)node.style.transform='';if(go&&target>=0&&target<state.nodes.length)flipTo(target,{clearTrail:true,focus:true})};stage.addEventListener('pointerup',end);stage.addEventListener('pointercancel',end)}
function build(){if(state.built)return;state.root=document.getElementById('tome');if(!state.root)return;state.pages=data.pages;state.reduce=root.matchMedia?.('(prefers-reduced-motion: reduce)').matches;const shell=node('div','tome-shell'),header=node('header','codex-header tome-header'),back=UI.iconButton({icon:'back',label:'Back to Home',framed:true,onClick:()=>root.ebNavigate('home',{direction:'back'})});back.classList.add('codex-back');const searchButton=UI.iconButton({icon:'search',label:'Search the Tome',framed:true,onClick:()=>openSearch(searchButton)});searchButton.classList.add('tome-search-button');header.append(back,node('h1','codex-title','How to Play'),searchButton);const layout=node('div','tome-layout'),book=node('div','tome-book'),stage=node('div','tome-stage');state.book=book;state.nodes=state.pages.map((page,index)=>renderPage(page,index));stage.append(...state.nodes);book.append(stage);const tabs=node('nav','tome-tabs');tabs.setAttribute('aria-label','Tome chapters');state.tabs=data.chapters.map(chapter=>{const button=node('button','tome-tab');button.type='button';button.dataset.chapter=chapter.id;button.setAttribute('aria-label',chapter.label);button.append(chapter.element?medallion(chapter.element):icon(chapter.tabIcon,chapter.label));button.addEventListener('click',()=>{const index=chapterFirst.get(chapter.id);if(index>=0)flipTo(index,{clearTrail:true,focus:true})});tabs.append(button);return button});layout.append(book,tabs);const nav=node('div','tome-nav'),prev=UI.iconButton({icon:'back',label:'Previous page',framed:true,onClick:()=>flipTo(state.current-1,{clearTrail:true,focus:true})}),label=node('span','tome-nav-label'),next=UI.iconButton({icon:'back',label:'Next page',framed:true,onClick:()=>flipTo(state.current+1,{clearTrail:true,focus:true})});prev.classList.add('tome-prev');next.classList.add('tome-next','is-next');nav.append(prev,label,next);const live=node('div','tome-live');live.setAttribute('aria-live','polite');live.classList.add('eb-sr-only');shell.append(header,layout,nav,live);state.root.append(shell);bindSwipe(stage);document.addEventListener('keydown',event=>{if(!state.root.classList.contains('on')||event.target.closest('input,textarea,select'))return;if(event.key==='ArrowLeft'||event.key==='ArrowRight'){event.preventDefault();flipTo(state.current+(event.key==='ArrowRight'?1:-1),{clearTrail:true,focus:true})}});state.built=true;renderWindow()}
  function focusAfterNavigation(target){setTimeout(()=>{if(state.root.classList.contains('on')&&target.isConnected)target.focus({preventScroll:true})},state.reduce?170:450)}
  function cover(){const cover=node('div','tome-cover'),logo=node('img','tome-cover-logo');logo.src='assets/images/logo.webp';logo.alt='Element Bound';const title=node('h2','','The Bender’s Tome'),subtitle=node('p','','Lessons & Glossary'),open=node('button','primary','Open the Tome');open.type='button';cover.append(logo,title,subtitle,open);state.book.append(cover);requestAnimationFrame(()=>open.focus({preventScroll:true}));focusAfterNavigation(open);open.addEventListener('click',()=>{cover.classList.add('is-open');state.root.classList.add('is-tome-open');setTimeout(()=>{cover.remove();state.nodes[state.current].querySelector('.tome-title')?.focus({preventScroll:true})},state.reduce?150:800)});return cover}
  function open(){lessons.markOpened();build();if(!state.built)return api;renderWindow();if(!state.opened){state.opened=true;state.root.classList.remove('is-tome-open');cover()}else{state.root.classList.add('is-tome-open');focusAfterNavigation(state.nodes[state.current].querySelector('.tome-title'))}return api}

  const peekState={overlay:null,sheet:null,body:null,stack:[],opener:null,closing:false};
  function peekFocus(){const target=peekState.body.querySelector('.tome-search-input,[data-sheet-autofocus]')||peekState.body.querySelector('.tome-title,.codex-card-name');if(target){if(!target.matches('input'))target.tabIndex=-1;target.focus({preventScroll:true})}}
  function peekRender(){const stack=peekState.stack,entry=stack[stack.length-1],prev=stack[stack.length-2];let back=null;if(prev){back=node('button','tome-ribbon',`‹ Back to ${prev.label}`);back.type='button';back.addEventListener('click',()=>{stack.pop();peekRender()})}let content;
    if(entry.type==='custom'){content=entry.render({close:(restoreFocus=true)=>{if(!restoreFocus)peekState.opener=null;closePeek()}})}
    else if(entry.type==='search'){content=renderSearch(entry)}
    else if(entry.type==='term'){const index=titleIndex.get(entry.title);linkHandler=title=>{const resolved=resolveTitle(title);if(resolved){stack.push({type:'term',title:resolved,label:resolved});peekRender()}};try{content=renderPage(data.pages[index],index,{peek:true,ribbon:back})}finally{linkHandler=null}content.removeAttribute('aria-hidden');content.classList.add('is-current')}
    else{content=node('article','tome-page tome-peek-card is-current');const scroll=node('div','tome-page-scroll');if(back)scroll.append(back);const detail=root.EB_CardBrowser?.cardDetail?.(entry.name);if(detail)scroll.append(...detail);else scroll.append(node('p','tome-rule',entry.name));content.append(scroll)}
    peekState.body.replaceChildren(content);peekState.body.scrollTop=0;if(peekState.overlay.classList.contains('is-open'))peekFocus()}
  function peekKeydown(event){if(!peekState.overlay)return;if(event.key==='Escape'){event.preventDefault();event.stopImmediatePropagation();closePeek();return}if(event.key!=='Tab')return;event.stopImmediatePropagation();const items=[...peekState.sheet.querySelectorAll('button:not([disabled]),[href],[tabindex]:not([tabindex="-1"])')];if(!items.length)return;const first=items[0],last=items[items.length-1];if(event.shiftKey&&document.activeElement===first){event.preventDefault();last.focus()}else if(!event.shiftKey&&document.activeElement===last){event.preventDefault();first.focus()}}
  function closePeek(){const overlay=peekState.overlay;if(!overlay||peekState.closing)return;peekState.closing=true;const opener=peekState.opener,reduce=root.matchMedia?.('(prefers-reduced-motion: reduce)').matches;document.removeEventListener('keydown',peekKeydown,true);overlay.classList.remove('is-open');overlay.classList.add('is-closing');setTimeout(()=>{overlay.remove();peekState.overlay=null;peekState.sheet=null;peekState.body=null;peekState.stack=[];peekState.opener=null;peekState.closing=false;if(opener&&opener.isConnected)opener.focus({preventScroll:true})},reduce?150:280)}
  function openPeek(entry,opener){if(peekState.closing)return false;if(peekState.overlay){peekState.stack.push(entry);peekRender();return true}
    const overlay=node('div',`tome-peek-backdrop${entry.type==='search'||entry.top?' is-search':''}`),sheet=UI.sheet({variant:'info',children:[]});sheet.classList.add('tome-peek');sheet.setAttribute('role','dialog');sheet.setAttribute('aria-modal','true');sheet.setAttribute('aria-label',entry.type==='custom'?entry.label:'The Bender’s Tome');const close=UI.iconButton({icon:'close',label:'Close',framed:true,onClick:closePeek});close.classList.add('tome-peek-close');const body=node('div','tome-peek-body');sheet.append(close,body);overlay.append(sheet);overlay.addEventListener('click',event=>{if(event.target===overlay)closePeek()});
    Object.assign(peekState,{overlay,sheet,body,stack:[entry],opener:opener||document.activeElement});document.body.append(overlay);peekRender();document.addEventListener('keydown',peekKeydown,true);requestAnimationFrame(()=>requestAnimationFrame(()=>{overlay.classList.add('is-open');peekFocus()}));return true}

  function norm(value){return String(value||'').toLowerCase().normalize('NFD').replace(/[̀-ͯ]/g,'').replace(/\[\[|\]\]/g,'').replace(/[^a-z0-9 ]+/g,' ').replace(/\s+/g,' ').trim()}
  const searchIndex=(data?.pages||[]).map((page,index)=>({index,page,title:norm(page.title),text:norm([page.archivist,page.rule,page.rules,page.confuse,page.deckLine].filter(Boolean).join(' '))}));
  const synonymIndex=[];for(const [title,words] of Object.entries(data?.synonyms||{}))for(const word of words)synonymIndex.push({word:norm(word),title});
  function searchTome(query){const q=norm(query);if(q.length<2)return[];const scored=new Map();const add=(index,score,via)=>{const prev=scored.get(index);if(!prev||score>prev.score)scored.set(index,{index,score,via})};
    for(const entry of searchIndex){if(entry.page.kind==='contents')continue;if(entry.title===q)add(entry.index,100);else if(entry.title.startsWith(q))add(entry.index,80);else if(entry.title.includes(q))add(entry.index,60);else if(q.length>=3&&entry.text.includes(q))add(entry.index,20)}
    for(const synonym of synonymIndex)if(synonym.word===q||(q.length>=3&&synonym.word.startsWith(q))){const index=titleIndex.get(synonym.title);if(index!==undefined)add(index,synonym.word===q?70:50,synonym.word)}
    return[...scored.values()].sort((a,b)=>b.score-a.score||a.index-b.index).slice(0,12)}
  function renderSearch(entry){const wrap=node('div','tome-search');const heading=node('h2','tome-search-title','Search the Tome');heading.id='tomeSearchTitle';const input=node('input','tome-search-input');input.type='search';input.placeholder='A word, a symbol, an element…';input.setAttribute('aria-label','Search the Tome');input.setAttribute('aria-describedby','tomeSearchStatus');input.autocomplete='off';input.spellcheck=false;input.value=entry.query||'';const status=node('p','tome-search-status');status.id='tomeSearchStatus';status.setAttribute('aria-live','polite');const list=node('div','tome-search-results');
    const go=index=>{peekState.opener=null;closePeek();flipTo(index,{clearTrail:true,focus:true})};
    const update=()=>{entry.query=input.value;const results=searchTome(input.value);list.replaceChildren();if(norm(input.value).length<2){status.textContent='Try a word from any card game: mana, graveyard, taunt.';return}if(!results.length){status.textContent='The Tome has no page for that. Try another word.';return}status.textContent=`${results.length} ${results.length===1?'page':'pages'} found.`;
      for(const result of results){const page=data.pages[result.index],button=node('button','tome-search-result');button.type='button';button.append(page.kind==='element'?medallion(page.element,'tome-search-medallion'):icon(page.icon||'book'));const copy=node('span','tome-search-copy');copy.append(node('strong','',page.title),node('small','',result.via?`Also called “${result.via}”`:sectionLabel(page)));button.append(copy);button.addEventListener('click',()=>go(result.index));list.append(button)}
      glyphify(list)};
    input.addEventListener('input',update);input.addEventListener('keydown',event=>{if(event.key==='Enter'){const first=list.querySelector('.tome-search-result');if(first){event.preventDefault();first.click()}}});
    wrap.append(heading,input,status,list);update();return wrap}
  function openSearch(opener){return openPeek({type:'search',label:'Search',query:''},opener)}
  function peek(term,opener){const title=resolveTitle(term);if(!title)return false;return openPeek({type:'term',title,label:title},opener)}
  function peekCard(name,opener){return openPeek({type:'card',name,label:name},opener)}
  if(document)document.addEventListener('click',event=>{const trigger=event.target.closest?.('[data-tome-term]');if(!trigger)return;if(peek(trigger.dataset.tomeTerm,trigger)){event.preventDefault();event.stopPropagation()}});
  const api={open,flipTo,followLink,peek,peekCard,closePeek,openSearch,sheet:(options,opener)=>openPeek({type:'custom',label:options.label,top:!!options.top,render:options.render},opener),search:searchTome,has:term=>!!resolveTitle(term),get current(){return state.current},get pages(){return state.pages}};return api;
});
