(function(root,factory){
  const api=factory(root,root&&root.document,root&&root.EB_UI,root&&root.EB_TOME);
  if(typeof module==='object'&&module.exports)module.exports=api;
  if(root)root.EB_Tome=api;
})(typeof globalThis!=='undefined'?globalThis:this,function(root,document,UI,data){
  'use strict';
  const state={root:null,book:null,pages:[],nodes:[],tabs:[],current:0,trail:[],opened:false,built:false,reduce:false,drag:null,timer:0};
  const titleIndex=new Map((data?.pages||[]).map((page,index)=>[page.title,index]));
  const chapterFirst=new Map((data?.chapters||[]).map(chapter=>[chapter.id,(data?.pages||[]).findIndex(page=>page.chapter===chapter.id)]));
  function node(tag,className,text){const el=document.createElement(tag);if(className)el.className=className;if(text!==undefined)el.textContent=text;return el}
  function icon(name,label){return UI.icon(name,{label})}
  function medallion(element,className=''){const image=node('img',`tome-medallion ${className}`);image.src=`assets/medallions/${element.toLowerCase()}.webp`;image.alt='';return image}
  function plain(value=''){return String(value).replace(/\*\*/g,'')}
  function appendLinked(container,text){
    const parts=String(text||'').split(/(\[\[[^\]]+\]\])/g);for(const part of parts){const match=part.match(/^\[\[([^\]]+)\]\]$/);if(!match){container.append(document.createTextNode(part));continue}const button=node('button','tome-link',match[1]);button.type='button';button.addEventListener('click',()=>followLink(match[1]));container.append(button)}
  }
  function linkChip(title){const button=node('button','tome-chip',`${title} ›`);button.type='button';button.addEventListener('click',event=>{event.stopPropagation();followLink(title)});return button}
  function facts(page){const row=node('div','tome-facts');for(const [key,label] of [['on','On'],['lasts','Lasts'],['stacks','Stacks']]){const badge=node('span','tome-fact');badge.append(node('small','',label),node('strong','',page.facts[key]));row.append(badge)}return row}
  function staticDemo(page){const demo=node('div','tome-demo');demo.setAttribute('role','img');demo.setAttribute('aria-label',page.demo);const glyph=icon(page.icon||'sparkle',page.title);const copy=node('span','',page.demo);demo.append(glyph,copy);return demo}
  function ribbon(){if(!state.trail.length)return null;const previous=state.pages[state.trail[state.trail.length-1]],button=node('button','tome-ribbon',`‹ Back to ${previous.title}`);button.type='button';button.addEventListener('click',()=>{const target=state.trail.pop();flipTo(target,{focus:true})});return button}
  function renderContents(body){
    const groups=[['Part One · First Lessons',state.pages.map((p,i)=>[p,i]).filter(([p])=>p.kind==='lesson')],['Part Two · The Glossary',state.pages.map((p,i)=>[p,i]).filter(([p])=>['term','symbol','glance','index'].includes(p.kind)).filter(([p])=>p.kind==='glance'||p.kind==='index'||p.title==='Attack ⚔')]];
    for(const [heading,items] of groups){body.append(node('h3','tome-section-title',heading));const list=node('div','tome-contents-list');for(const [page,index] of items){const button=node('button','tome-contents-row');button.type='button';button.append(node('span','',page.kind==='lesson'?page.label.split(' · ').pop():page.title==='Attack ⚔'?'Core Terms & Symbols':page.title),node('small','',String(index+1)));button.addEventListener('click',()=>flipTo(index,{clearTrail:true,focus:true}));list.append(button)}body.append(list)}
  }
  function renderGlance(body,page){const table=node('div','tome-glance');for(const item of page.table){const row=node('div','tome-glance-row');row.append(item.icon==='—'?node('span','tome-glance-icon','—'):icon(item.icon,item.effect));const link=node('button','tome-glance-name',item.effect);link.type='button';link.addEventListener('click',()=>followLink(item.effect));row.append(link,node('span','tome-glance-element',item.element),node('span','tome-glance-what',item.what),node('small','',`${item.lasts} · ${item.stacks}`));table.append(row)}body.append(table)}
  function renderIndex(body){for(const [label,elements] of [['Prime',['FIRE','WATER','EARTH','NATURE','LIGHTNING','AIR']],['Hybrid',['MAGMA','BLOOM','STORM']]]){body.append(node('h3','tome-section-title',label));const grid=node('div','tome-element-grid');for(const element of elements){const button=node('button','tome-element-button');button.type='button';button.setAttribute('aria-label',element[0]+element.slice(1).toLowerCase());button.append(medallion(element),node('span','',element[0]+element.slice(1).toLowerCase()));button.addEventListener('click',()=>flipTo(titleIndex.get(element[0]+element.slice(1).toLowerCase()),{clearTrail:true,focus:true}));grid.append(button)}body.append(grid)}body.append(node('p','tome-index-hint','Tap an element, or use the tabs on the page edge.'))}
  function tryButton(element){const info={FIRE:'Flame',WATER:'Tides',EARTH:'Stone',NATURE:'Roots',LIGHTNING:'Storms',AIR:'Winds'},button=node('button','primary tome-try',`Try it · Trial of ${info[element]}`);button.type='button';button.addEventListener('click',()=>{root.goTrials();requestAnimationFrame(()=>requestAnimationFrame(()=>{const target=document.querySelector(`.trial-map-node[data-element="${element}"]`);if(target)root.EB_Trials.openChapter(element,target)}))});return button}
  function renderPage(page,index){
    const article=node('article','tome-page');article.dataset.pageId=page.id;article.setAttribute('aria-hidden','true');const scroll=node('div','tome-page-scroll'),back=ribbon();if(back)scroll.append(back);scroll.append(node('div','tome-kind',page.label));const title=node('h2','tome-title');title.tabIndex=-1;if(page.kind==='element')title.append(medallion(page.element,'tome-title-medallion'));else title.append(icon(page.icon||'book'));title.append(document.createTextNode(page.title));scroll.append(title,node('div','tome-ornament'));
    if(page.archivist)scroll.append(node('p','tome-narr',page.archivist));
    if(page.kind==='contents')renderContents(scroll);else if(page.kind==='index')renderIndex(scroll);else if(page.kind==='glance')renderGlance(scroll,page);else{
      if(page.deckLine){const deck=node('p','tome-deck-line');deck.style.setProperty('--c',`var(--eb-el-${page.element.toLowerCase()})`);deck.textContent=plain(page.deckLine);scroll.append(deck)}
      if(page.rules){const rules=node('div','tome-rule');for(const line of String(page.rules).split(/(?<=\.)\s+/)){const p=node('p');appendLinked(p,line);rules.append(p)}scroll.append(rules)}
      if(page.rule){const rule=node('p','tome-rule');appendLinked(rule,page.rule);scroll.append(rule)}
      if(page.facts)scroll.append(facts(page));if(page.demo&&page.kind!=='lesson')scroll.append(staticDemo(page));
      if(page.confuse){const box=node('div','tome-confuse');box.append(node('b','','≠'),node('small','','Don’t confuse with'));const copy=node('p');appendLinked(copy,page.confuse);box.append(copy);scroll.append(box)}
      if(page.seenOn?.length){scroll.append(node('h3','tome-section-title','Seen on'));const chips=node('div','tome-chips');for(const card of page.seenOn)chips.append(node('span','tome-card-chip',card));scroll.append(chips)}
      for(const [field,label] of [['seeAlso','See also'],['inChapter','In this chapter'],['parents','Parents']])if(page[field]?.length){scroll.append(node('h3','tome-section-title',label));const chips=node('div','tome-chips');for(const link of page[field])chips.append(linkChip(link));scroll.append(chips)}
      if(page.hybrid){scroll.append(node('h3','tome-section-title','Hybrid'));const chips=node('div','tome-chips');chips.append(linkChip(page.hybrid));scroll.append(chips)}
      if(page.response){scroll.append(node('h3','tome-section-title','Response'),node('div','tome-response',page.response))}if(page.tryIt)scroll.append(tryButton(page.tryIt));
    }
    article.append(scroll);return article;
  }
  function sectionLabel(page){if(page.kind==='contents')return'Contents';if(page.kind==='lesson')return'First Lessons';if(page.kind==='glance')return'At a Glance';if(page.kind==='index')return'Elements';if(page.chapter==='core')return'Core Terms';return page.chapter[0]+page.chapter.slice(1).toLowerCase()}
  function renderWindow(){for(let index=0;index<state.nodes.length;index++){const visible=Math.abs(index-state.current)<=2,node=state.nodes[index];node.hidden=!visible;node.style.zIndex=String(state.nodes.length-index);node.classList.toggle('is-past',index<state.current);node.classList.toggle('is-current',index===state.current);node.setAttribute('aria-hidden',String(index!==state.current))}const page=state.pages[state.current];state.root.querySelector('.tome-nav-label').textContent=`${sectionLabel(page)} · ${state.current+1}`;state.root.querySelector('.tome-prev').disabled=state.current===0;state.root.querySelector('.tome-next').disabled=state.current===state.pages.length-1;for(const tab of state.tabs)tab.setAttribute('aria-current',tab.dataset.chapter===page.chapter?'page':'false');state.root.querySelector('.tome-live').textContent=`${page.title}, page ${state.current+1} of ${state.pages.length}`}
  function rebuildCurrent(){const old=state.nodes[state.current],fresh=renderPage(state.pages[state.current],state.current);old.replaceWith(fresh);state.nodes[state.current]=fresh}
  function flipTo(index,{push=false,clearTrail=false,focus=false}={}){index=Math.max(0,Math.min(state.pages.length-1,index));if(index===state.current){if(focus)state.nodes[index].querySelector('.tome-title')?.focus({preventScroll:true});return}if(push){state.trail.push(state.current);state.trail=state.trail.slice(-10)}if(clearTrail)state.trail=[];clearTimeout(state.timer);state.book.classList.add('is-flipping');state.current=index;rebuildCurrent();renderWindow();state.reduce=root.matchMedia?.('(prefers-reduced-motion: reduce)').matches;state.timer=setTimeout(()=>{state.book.classList.remove('is-flipping');if(focus)state.nodes[index].querySelector('.tome-title')?.focus({preventScroll:true})},state.reduce?150:620)}
  function followLink(title){const index=titleIndex.get(title);if(index!==undefined)flipTo(index,{push:true,focus:true})}
  function bindSwipe(stage){stage.addEventListener('pointerdown',event=>{if(event.button!==0)return;state.drag={id:event.pointerId,start:event.clientX,last:event.clientX,time:performance.now(),lastTime:performance.now()};stage.setPointerCapture(event.pointerId)});stage.addEventListener('pointermove',event=>{if(!state.drag||state.drag.id!==event.pointerId)return;const dx=event.clientX-state.drag.start,width=stage.clientWidth||1,progress=Math.max(-1,Math.min(1,-dx/width));state.nodes[state.current].style.transform=`rotateY(${-178*Math.max(0,progress)}deg)`;state.drag.last=event.clientX;state.drag.lastTime=performance.now()});const end=event=>{if(!state.drag||state.drag.id!==event.pointerId)return;const drag=state.drag;state.drag=null;const dx=event.clientX-drag.start,elapsed=Math.max(1,performance.now()-drag.time),speed=Math.abs(dx)/elapsed,go=Math.abs(dx)>stage.clientWidth*.25||speed>.3;state.nodes[state.current].style.transform='';if(go)flipTo(state.current+(dx<0?1:-1),{clearTrail:true,focus:true})};stage.addEventListener('pointerup',end);stage.addEventListener('pointercancel',end)}
  function build(){if(state.built)return;state.root=document.getElementById('tome');if(!state.root)return;state.pages=data.pages;state.reduce=root.matchMedia?.('(prefers-reduced-motion: reduce)').matches;const shell=node('div','tome-shell'),header=node('header','codex-header tome-header'),back=UI.iconButton({icon:'back',label:'Back to Home',framed:true,onClick:()=>root.ebNavigate('home',{direction:'back'})});back.classList.add('codex-back');header.append(back,node('h1','codex-title','How to Play'),node('span','codex-header-spacer'));const layout=node('div','tome-layout'),book=node('div','tome-book'),stage=node('div','tome-stage');state.book=book;state.nodes=state.pages.map((page,index)=>renderPage(page,index));stage.append(...state.nodes);book.append(stage);const tabs=node('nav','tome-tabs');tabs.setAttribute('aria-label','Tome chapters');state.tabs=data.chapters.map(chapter=>{const button=node('button','tome-tab');button.type='button';button.dataset.chapter=chapter.id;button.setAttribute('aria-label',chapter.label);button.append(chapter.element?medallion(chapter.element):icon(chapter.tabIcon,chapter.label));button.addEventListener('click',()=>{const index=chapterFirst.get(chapter.id);if(index>=0)flipTo(index,{clearTrail:true,focus:true})});tabs.append(button);return button});layout.append(book,tabs);const nav=node('div','tome-nav'),prev=UI.iconButton({icon:'back',label:'Previous page',framed:true,onClick:()=>flipTo(state.current-1,{clearTrail:true,focus:true})}),label=node('span','tome-nav-label'),next=UI.iconButton({icon:'back',label:'Next page',framed:true,onClick:()=>flipTo(state.current+1,{clearTrail:true,focus:true})});prev.classList.add('tome-prev');next.classList.add('tome-next','is-next');nav.append(prev,label,next);const live=node('div','tome-live');live.setAttribute('aria-live','polite');live.classList.add('eb-sr-only');shell.append(header,layout,nav,live);state.root.append(shell);bindSwipe(stage);document.addEventListener('keydown',event=>{if(!state.root.classList.contains('on')||event.target.closest('input,textarea,select'))return;if(event.key==='ArrowLeft'||event.key==='ArrowRight'){event.preventDefault();flipTo(state.current+(event.key==='ArrowRight'?1:-1),{clearTrail:true,focus:true})}});state.built=true;renderWindow()}
  function focusAfterNavigation(target){setTimeout(()=>{if(state.root.classList.contains('on')&&target.isConnected)target.focus({preventScroll:true})},state.reduce?170:400)}
  function cover(){const cover=node('div','tome-cover'),logo=node('img','tome-cover-logo');logo.src='assets/images/logo.webp';logo.alt='Element Bound';const title=node('h2','','The Bender’s Tome'),subtitle=node('p','','Lessons & Glossary'),open=node('button','primary','Open the Tome');open.type='button';cover.append(logo,title,subtitle,open);state.book.append(cover);requestAnimationFrame(()=>open.focus({preventScroll:true}));focusAfterNavigation(open);open.addEventListener('click',()=>{cover.classList.add('is-open');state.root.classList.add('is-tome-open');setTimeout(()=>{cover.remove();state.nodes[state.current].querySelector('.tome-title')?.focus({preventScroll:true})},state.reduce?150:800)});return cover}
  function open(){build();if(!state.built)return api;renderWindow();if(!state.opened){state.opened=true;state.root.classList.remove('is-tome-open');cover()}else{state.root.classList.add('is-tome-open');focusAfterNavigation(state.nodes[state.current].querySelector('.tome-title'))}return api}
  const api={open,flipTo,followLink,get current(){return state.current},get pages(){return state.pages}};return api;
});
