'use strict';
const assert=require('node:assert/strict');
const fs=require('node:fs');
let checks=0;
const read=file=>fs.readFileSync(file,'utf8');
const ok=(value,message)=>{assert.ok(value,message);checks++};
const card=read('css/cardBrowser.css'),deck=read('css/deckselect.css'),tokens=read('css/tokens.css'),script=read('js/deckSelect.js'),version=read('js/version.js'),design=read('docs/DESIGN.md');
ok(card.includes('.card-browser.is-animating .codex-dial-option'),'settle transition uses the shared browser root');
ok(!card.includes('.codex-shell.is-animating'),'no shared settle rule remains Codex-only');
ok(tokens.includes('--eb-ease-in:cubic-bezier(.4,0,1,1)'),'leaving easing token is defined');
ok(tokens.includes('--eb-ease-soft:cubic-bezier(.22,.61,.36,1)'),'arriving easing token is defined');
ok(/\.is-choosing-difficulty \.deckselect-grid-stage[^}]*transition-duration:200ms[^}]*transition-delay:0ms[^}]*var\(--eb-ease-in\)/.test(deck),'card grid leaves first over 200 ms');
ok(/\.is-choosing-difficulty \.deckselect-difficulty[^}]*transition-duration:400ms[^}]*transition-delay:160ms[^}]*var\(--eb-ease-soft\)/.test(deck),'difficulty panel arrives softly after 160 ms');
ok(/\.is-difficulty-interactive \.deckselect-difficulty\{pointer-events:auto\}/.test(deck)&&script.includes("interactionTimer=setTimeout(()=>browser.root.classList.add('is-difficulty-interactive'),160)"),'difficulty hit testing waits for the reveal');
ok(/nth-child\(1\)[^}]*220ms[\s\S]*nth-child\(2\)[^}]*280ms[\s\S]*nth-child\(3\)[^}]*340ms/.test(deck),'difficulty options are staggered by 60 ms');
ok(/prefers-reduced-motion:reduce[^}]*transition-duration:150ms;transition-delay:0ms;transition-timing-function:linear/.test(deck),'reduced motion removes delays and uses 150 ms linear fades');
ok(script.includes("heading.focus({preventScroll:true})"),'difficulty heading focus prevents scrolling');
const release=version.match(/version:'(\d+)\.(\d+)\.(\d+)'/);ok(release&&release.slice(1).map(Number).reduce((value,part)=>value*1000+part,0)>=1004002,'release metadata is at least 1.4.2');
ok(design.includes('the incoming panel starts about 160 ms later'),'motion choreography is documented');
console.log(`Deck motion 1.4.2: ${checks} checks passed`);
