'use strict';
const assert=require('node:assert/strict');
const fs=require('node:fs');
let checks=0;
const read=file=>fs.readFileSync(file,'utf8');
const ok=(value,message)=>{assert.ok(value,message);checks++};
const equal=(actual,expected,message)=>{assert.equal(actual,expected,message);checks++};
const card=read('css/cardBrowser.css'),deck=read('css/deckselect.css'),game=read('css/game.css'),tokens=read('css/tokens.css'),version=read('js/version.js'),design=read('docs/DESIGN.md');
ok(/\.codex-info\{position:relative;z-index:1;/.test(card),'zoom info paints above the card shadow');
ok(/\.codex-card-medallion--s\{width:26px;height:26px/.test(card),'small card medallion is compact');
ok(/\.codex-card-name[^}]*font:700 10px\/1\.05/.test(card),'small card names use compact type');
ok(/\.deckselect-stage\{position:relative;height:304px\}/.test(deck),'deck-select stage reserves the shared grid height');
ok(/\.deckselect-grid-stage[^}]*transition:/.test(deck),'step-aside animation lives on a dedicated wrapper');
ok(!/\.deckselect-shell \.codex-(dial|labels|dots|grids|grid-wrap)\{/.test(deck),'deck select does not override shared carousel geometry');
ok(!/dvh|\bvh\b/.test(deck),'deck select does not depend on viewport-height units');
ok(!/opacity:[^;}]*!important/.test(deck),'locked dial does not fight inline opacity');
ok(!/#setup::before/.test(deck),'legacy deck overlay is removed');
ok(!/--eb-overlay-deck/.test(tokens),'legacy deck overlay token is removed');
ok(/--eb-bg-blur:3px/.test(tokens)&&/--eb-bg-brightness:\.45/.test(tokens),'calm background tokens are defined');
ok(/body::before\{[\s\S]*filter:blur\(var\(--eb-bg-blur\)\) saturate\(\.8\) brightness\(var\(--eb-bg-brightness\)\)/.test(game),'body owns the static calm background');
ok(!/body::before\{[^}]*backdrop-filter/.test(game),'calm background avoids backdrop-filter');
ok(/version:'1\.4\.1'/.test(version)&&/label:'Deck polish'/.test(version),'release metadata identifies 1.4.1');
ok(design.includes('Calm background (about 55% darker plus a soft blur)'), 'design decisions record the calm background');
equal((deck.match(/\.deckselect-shell \.codex-card-grid\{/g)||[]).length,1,'only the permitted deck grid override remains');
console.log(`Deck polish 1.4.1: ${checks} checks passed`);
