'use strict';
const assert=require('node:assert/strict');
const fs=require('node:fs');
let checks=0;
const ok=(value,message)=>{assert.ok(value,message);checks++};
const equal=(actual,expected,message)=>{assert.equal(actual,expected,message);checks++};
const game=fs.readFileSync('js/game.js','utf8');
const menu=fs.readFileSync('css/menu.css','utf8');
const deck=fs.readFileSync('css/deckselect.css','utf8');
const tokens=fs.readFileSync('css/tokens.css','utf8');
const html=fs.readFileSync('index.html','utf8');
const version=fs.readFileSync('js/version.js','utf8');
ok(game.includes("function ebNavigate(toId,{direction='forward'}={})"),'one menu navigation function exists');
ok(!/ebDeckPush|ebFriendsPush/.test(game),'duplicated deck and Friends navigation functions are removed');
ok(!/ebDeckIn|ebHomeOut|ebHomeIn|ebDeckOut/.test(menu+deck),'asymmetric menu keyframes are removed');
ok(tokens.includes('--eb-ease-move:cubic-bezier(.65,0,.35,1)'),'symmetric movement easing token exists');
ok(menu.includes('translateX(-100%)')&&menu.includes('translateX(100%)'),'menu screens move the full viewport width in both directions');
ok(menu.includes('380ms var(--eb-ease-move)'),'menu push uses the specified timing');
ok(menu.includes('ebMenuFadeIn 150ms')&&menu.includes('ebMenuFadeOut 150ms'),'reduced motion uses a 150 ms cross-fade');
ok(html.includes('id="mpDeck" aria-hidden="true" tabindex="-1"'),'authoritative online select stays in the DOM and outside the accessibility tree');
ok(html.includes('id="mpDeckPicker"')&&html.includes('aria-haspopup="listbox"'),'custom deck trigger exposes its listbox relationship');
ok(game.includes("sheet.setAttribute('role','listbox')")&&game.includes("option.setAttribute('role','option')"),'deck sheet has listbox and option semantics');
ok(game.includes("select.dispatchEvent(new Event('change',{bubbles:true}))"),'custom selection dispatches change on the authoritative select');
const release=version.match(/version:'(\d+)\.(\d+)\.(\d+)'/);ok(release,'release metadata contains a semantic version');
ok(release.slice(1).map(Number).some((part,index,parts)=>part>[1,5,1][index]&&parts.slice(0,index).every((value,prior)=>value===[1,5,1][prior]))||release.slice(1).map(Number).every((part,index)=>part===[1,5,1][index]),'release metadata remains at least 1.5.1');
console.log(`Menu transitions 1.5.1: ${checks} checks passed`);
